config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "home", to: "static_pages#home"
  get "help", to: "static_pages#help"
  get "contact", to: "static_pages#contact"
  get "about", to: "static_pages#about"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users do
    member do
      resources :activities, only: [:index]
    end
  end
  resources :categories, only: [:index, :show]
  resources :lessons
  resources :words, only: [:index, :show]
  resources :followers
  resources :followings
  resources :relationships, only: [:create, :destroy]


  namespace :admin do
    resources :categories
    resources :users, except: [:edit, :update]
    resources :words
    resources :csv, only: [:index, :create]
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category

  has_many :answers, dependent: :destroy, inverse_of: :word
  has_many :results

  delegate :name, to: :category, prefix: true

  validates :content, presence: true, length: {maximum: 50},
    uniqueness: {case_sensitive: false}

  scope :all_words, -> user_id, search {where QUERY_BY_CONTENT, search: "%#{search}%"}
  scope :learnt, -> user_id, search {where QUERY_LEARNT, user_id: user_id,
    search: "%#{search}%"}
  scope :not_learnt, -> user_id, search {where QUERY_NOT_LEARNT, user_id: user_id,
    search: "%#{search}%"}
  scope :in_category, -> category_id do
    where category_id: category_id if category_id.present?
  end

  QUERY_BY_CONTENT = "content like :search"
  QUERY_LEARNT = "content like :search AND id IN(
    SELECT word_id FROM results r INNER JOIN lessons l ON r.lesson_id = l.id
     WHERE l.user_id = :user_id)"
  QUERY_NOT_LEARNT = "content like :search AND id NOT IN(
    SELECT word_id FROM results r INNER JOIN lessons l ON r.lesson_id = l.id
     WHERE l.user_id = :user_id)"

  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc{|attributes| attributes["content"].blank?}

  validate :check_answers

  class << self

    def list_words
      self.order(created_at: :ASC).includes(:category)
    end

    def import
      CSV.foreach(file.path, headers: true, col_sep: "|", header_converters: :symbol) do |row|
        row = row.to_hash
        answers_attributes = []
        row[:answers].split(";").each do |answer|
          answer_hash = Hash.new
          arr_answer = answer.split(",")
          answer_hash[:content] = arr_answer[0]
          answer_hash[:is_correct] = arr_answer[1]
          answers_attributes.push answer_hash
        end
        row[:answers_attributes] = answers_attributes
        row.delete :answers
        Word.create row
      end
    end

    def export
      attributes = %w{id content category_id}
      CSV.generate do |csv|
        csv << attributes
        all.each do |item|
          csv << attributes.map{|attr| item.send(attr)}
        end
      end
    end
  end

  private
  def check_answers
    size_correct = self.answers.select{|answer| answer.is_correct}.size
    if size_correct == 0
      errors.add I18n.t("validate.answer"), I18n.t("validate.zero")
    end
    if size_correct > 1
      errors.add I18n.t("validate.answer"), I18n.t(".required_1_correct")
    end
    if answers.length > answers.group_by { |a| a[:content] }.length
      self.errors.add :answers, I18n.t("validate.duplication")
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user, :verify_admin
  before_action :load_word, except: [:new, :create, :index]
  before_action :load_all_categories, except: [:show, :destroy]

  def new
    @word = Word.new
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t ".create_word_success"
      redirect_to @word
    else
      render :new
    end
  end

  def index
    params[:search] ||= ""
    @words = Word.list_words.in_category(params[:category_id])
      .all_words(current_user.id, params[:search])
      .paginate page: params[:page], per_page: Settings.word.per_page
  end

  def show
    @answers = @word.answers
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t ".update_success", name: @word.content
    else
      flash[:info] = t ".update_fail", name: @word.content
    end
    redirect_to [:admin, @word]
  end

  def destroy
    if @word.destroy
      flash[:success] = t ".deleted", name: @word.content
    else
      flash[:info] = t ".deleted_fail", name: @word.content
    end
    redirect_to admin_words_path
  end

  private
  def word_params
    params.require(:word).permit :category_id, :content,
      answers_attributes: [:id, :content, :is_correct, :_destroy]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :load_all_categories, only: [:index]
  before_action :logged_in_user, only: [:index, :show]

  def index
    params[:search] ||= ""
    params[:status] ||= Settings.word.filter.first
    @words = Word.in_category(params[:category_id])
      .send(params[:status], current_user.id, params[:search])
      .paginate page: params[:page], per_page: Settings.word.per_page
  end
end

app/views/admin/words/_answer_fields.html.erb
<div class="form-group answer_field">
  <div class="row">
    <div class="col-md-6">
      <%= f.text_field :content, class: "form-control content-answer", require: true %>
    </div>
    <div class="col-md-3">
      <%= f.label :is_correct, t(".correct") %>
      <%= f.check_box :is_correct, class: "radio-answer" %>
    </div>
    <div class="col-md-3">
      <%= link_to_remove_fields t(".remove"), f %>
    </div>
  </div>
</div>

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <div class="form-group">
    <%= f.select :category_id, options_for_select(@categories.collect {|category|
      [category.name, category.id]}), class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :question %>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :answers %>
    <%= f.fields_for :answers do |builder| %>
      <%= render "answer_fields", f: builder %>
    <% end %>
  </div>
  <div class="form-group">
    <%= link_to_add_fields t(".add_answer"), f, :answers %>
  </div>
  <div class="action">
    <%= f.submit yield(:button_text), class: "btn btn-primary submit" %>
  </div>
<% end %>

app/views/admin/words/_word.html.erb
<tr class="each-word">
  <td class="col-md-1">
    <%= index_for word_counter, @words.current_page, Settings.word.per_page %>
  </td>
  <td class="col-md-3"><%= word.category.name %></td>
  <td class="col-md-4"><%= word.content %></td>
  <td class="col-md-4">
    <%= link_to t(".info"), [:admin, word], class: "btn btn-sm btn-info fa fa-eye" %>
    <%= link_to t(".edit"), edit_admin_word_path(word), class: "btn btn-sm btn-warning fa fa-pencil" %>
    <%= link_to t(".delete"), [:admin, word], method: :delete,
      data: {confirm: t(".sure?")}, class: "btn btn-sm btn-danger fa fa-trash" %>
  </td>
</tr>

app/views/admin/words/edit.html.erb
<% provide :title, t(".edit") %>
<% provide :button_text, t(".save") %>

<h1><%= t ".edit" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/words/index.html.erb
<% provide :title, t(".all_words") %>

<h1><%= t ".all_words" %></h1>
<div class="row">
  <div class="search-row">
    <%= form_tag admin_words_path, method: :get do %>
      <div class="row">
        <div class="col-md-4 col-md-offset-2">
          <%= select_tag :category_id, options_for_select(@categories.collect{|category|
            [category.name, category.id]}, params[:category_id]), class: "form-control" %>
        </div>
        <div class="col-md-4 input-group">
          <%= text_field_tag :search, params[:search],
            placeholder: t(".search"), class: "form-control search-field" %>
          <div class="input-group-btn search-btn">
            <%= button_tag type: "submit", class: "btn btn-primary" do %>
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
              <span class="label-icon"><%= t ".search" %></span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
    <div class="new_word">
      <%= link_to new_admin_word_path do %>
        <span class="btn btn-primary glyphicon glyphicon-plus"></span>
      <% end %>
    </div>
  </div>
  <div class="col-md-2">
    <div class="btn btn-info import">
      <i class="fa fa-upload"></i> <%= t ".import" %>
    </div>
  </div>
  <div class="col-sm-4" id="import" style="display: none">
    <%= form_tag admin_csv_index_path, multipart: true do %>
      <div class="import_file">
        <%= file_field_tag :file %>
      </div>
      <div class="import_file">
        <%= submit_tag t(".submit") %>
      </div>
    <% end %>
  </div>
</div>
<div class="panel-body">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="table-responsive">
        <table class="table table-hover table-bordered">
          <thead>
            <tr>
              <th><%= t ".number" %></th>
              <th><%= t ".category" %></th>
              <th><%= t ".content" %></th>
              <th><%= t ".action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @words %>
          </tbody>
        </table>
        <%= will_paginate @words %>
      </div>
    </div>
  </div>
</div>

app/views/admin/words/new.html.erb
<% provide :title, t(".add_word") %>
<% provide :button_text, t(".create_word") %>

<h1><%= t ".add_word" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/words/show.html.erb
<% provide :title, t(".word_detail", name: @word.content) %>

<h1><%= t ".word_detail", name: @word.content %></h1>
<div class="edit_word">
  <%= link_to edit_admin_word_path(@word) do  %>
    <span class="btn btn-primary fa fa pencil pull-right"><%= t ".edit" %></span>
  <% end %>
</div>
<div class="row">
  <div class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th><%= t ".content" %></th>
          <th><%= t ".category" %></th>
          <th><%= t ".answers" %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @word.content %></td>
          <td><%= @word.category_name %></td>
          <td>
            <% if @answers.any? %>
              <ul class="list_answers">
                <% @answers.each do |answer| %>
                  <li class="each_answer">
                    <%= answer.content %>
                    <% if answer.is_correct %>
                      <span class="glyphicon glyphicon-ok"></span>
                    <% else %>
                      <span class="glyphicon glyphicon-remove"></span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            <% else %>
              <p><%= t ".no_answer", name: @word.content %>.</p>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>