config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "home", to: "static_pages#home"
  get "help", to: "static_pages#help"
  get "contact", to: "static_pages#contact"
  get "about", to: "static_pages#about"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users do
    member do
      resources :activities, only: [:index]
    end
  end
  resources :categories, only: [:index, :show]
  resources :lessons
  resources :words, only: [:index, :show]
  resources :followers
  resources :followings
  resources :relationships, only: [:create, :destroy]


  namespace :admin do
    resources :categories
    resources :users, except: [:edit, :update]
    resources :words
    resources :csv, only: [:index, :create]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form_contains" %> <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_path @user %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t ".following" %>
  </a>
  <a href="<%= follower_path @user %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t ".followers" %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<h3>
  <%= image_tag @user.avatar? ? @user.avatar.url :
    Settings.image, class: "img-responsive" %>
  <%= @user.name %>
</h3>
<span><%= link_to t(".view_profile"), @user %></span>