config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "home", to: "static_pages#home"
  get "help", to: "static_pages#help"
  get "contact", to: "static_pages#contact"
  get "about", to: "static_pages#about"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users do
    member do
      resources :activities, only: [:index]
    end
  end
  resources :categories, only: [:index, :show]
  resources :lessons
  resources :words, only: [:index, :show]
  resources :followers
  resources :followings
  resources :relationships, only: [:create, :destroy]


  namespace :admin do
    resources :categories
    resources :users, except: [:edit, :update]
    resources :words
    resources :csv, only: [:index, :create]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words
  has_many :lessons

  validates :name, presence: true, length: {maximum: 50},
    uniqueness: {case_sensitive: false}
  validates :description, presence: true, length: {maximum: 255}, allow_nil: true

  scope :all_categories, -> search {where QUERY_BY_NAME, search: "%#{search}%"}
  QUERY_BY_NAME = "name like :search"
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :load_category, except: [:new, :create, :index]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".created"
      redirect_to [:admin, @category]
    else
      flash.now[:danger] = t ".not_created"
    end
  end

  def index
    params[:search] ||= ""
    @categories = Category.all_categories(params[:search])
      .paginate page: params[:page], per_page: Settings.category.per_page
  end

  def show
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".updated", name: @category.name
    else
      flash[:info] = t ".not_updated", name: @category.name
    end
    redirect_to admin_categories_path
  end

  def destroy
    if @category.words.any?
      flash[:notice] = t ".notice_mess"
    elsif @category.destroy
      flash[:success] = t ".deleted", name: @category.name
    else
      flash[:danger] = t ".not_deleted", name: @category.name
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.permit :name, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
    render_404 unless @category
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    params[:search] ||= ""
    @categories = Category.order(created_at: :ASC)
      .all_categories(params[:search]).includes(:words)
      .paginate page: params[:page], per_page: Settings.category.per_page
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr class="category-row">
  <td class="col-md-1"><%= index_for category_counter, @categories.current_page,
    Settings.category.per_page %></td>
  <td class="col-md-2"><%= link_to category.name, words_path(category_id: category.id) %></td>
  <td class="col-md-4"><%= category.description %></td>
  <td class="col-md-2"><%= category.words.count %></td>
  <td class="col-md-3">
    <div class="btn btn-sm btn-primary">
      <i class="fa fa-play" aria-hidden="true"></i>
      <%= link_to t(".start"), lessons_path(category_id: category.id), method: :post,
       class: "btn-primary" %>
    </div>
  </td>
</tr>

app/views/categories/index.html.erb
<% provide :title, t(".all_categories") %>

<h1><%= t ".all_categories" %></h1>
<div class="row">
  <div class="search-form">
    <%= form_tag categories_path, method: :get, id: "search-form" do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], placeholder: t(".search"),
          class: "form-control search-field" %>
        <div class="input-group-btn search-btn">
          <%= button_tag type: "submit", class: "btn btn-primary" do %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            <span class="label-icon"><%= t ".search" %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="panel-body">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <table class="table table-hover table-bordered table-responsive th-word">
        <thead class="th-word">
          <th class="th-index"><%= t ".number" %></th>
          <th class="th-category"><%= t ".name" %></th>
          <th class="th-category"><%= t ".description" %></th>
          <th class="th-category"><%= t ".words_total" %></th>
          <th class="th-category"><%= t ".action" %></th>
        </thead>
        <tbody>
          <%= render @categories %>
        </tbody>
      </table>
      <%= will_paginate @categories %>
    </div>
  </div>
</div>